baseURL = 'https://thomjur.github.io/idk-website/'
languageCode = 'en-us'
title = 'IDK-Website'
theme = 'idk-theme'
relativeURLs = true          # Relative URLs verwenden
canonifyURLs = true          # URLs in absolute Pfade umwandeln

[menu]
  [[menu.main]]
    name = "Aktuelles"
    url = "/aktuelles/"
    weight = 1

  [[menu.main]]
    name = "Chronik"
    url = "/chronik/"
    weight = 2

  [[menu.main]]
    name = "Konferenzen"
    url = "/konferenzen/"
    weight = 3

  [[menu.main]]
    name = "Impressum"
    url = "/about/"
    weight = 4
